/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UpdatePasswordRouteImport } from './routes/update-password'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ViewRouteRouteImport } from './routes/_view/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChangelogIndexRouteImport } from './routes/changelog/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as ChangelogVersionRouteImport } from './routes/changelog/$version'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as ApiTemplatesRouteImport } from './routes/api/templates'
import { Route as ApiShortcutsRouteImport } from './routes/api/shortcuts'
import { Route as ApiMediaUploadRouteImport } from './routes/api/media-upload'
import { Route as ViewAppRouteRouteImport } from './routes/_view/app/route'
import { Route as ViewAppIndexRouteImport } from './routes/_view/app/index'
import { Route as ApiWebhooksSlackInteractiveRouteImport } from './routes/api/webhooks/slack-interactive'
import { Route as ApiTweetIdRouteImport } from './routes/api/tweet.$id'
import { Route as ApiAssetsSplatRouteImport } from './routes/api/assets.$'
import { Route as ViewDownloadAppleSiliconRouteImport } from './routes/_view/download/apple-silicon'
import { Route as ViewDownloadAppleIntelRouteImport } from './routes/_view/download/apple-intel'
import { Route as ViewCallbackSignoutRouteImport } from './routes/_view/callback/signout'
import { Route as ViewCallbackIntegrationRouteImport } from './routes/_view/callback/integration'
import { Route as ViewCallbackBillingRouteImport } from './routes/_view/callback/billing'
import { Route as ViewCallbackAuthRouteImport } from './routes/_view/callback/auth'
import { Route as ViewAppSwitchPlanRouteImport } from './routes/_view/app/switch-plan'
import { Route as ViewAppPortalRouteImport } from './routes/_view/app/portal'
import { Route as ViewAppIntegrationRouteImport } from './routes/_view/app/integration'
import { Route as ViewAppCheckoutRouteImport } from './routes/_view/app/checkout'
import { Route as ViewAppAccountRouteImport } from './routes/_view/app/account'
import { Route as ApiOgBlogSlugRouteImport } from './routes/api/og/blog/$slug'
import { Route as ApiAdminStarsResearchRouteImport } from './routes/api/admin/stars/research'
import { Route as ApiAdminStarsPipelineRouteImport } from './routes/api/admin/stars/pipeline'
import { Route as ApiAdminStarsLeadsRouteImport } from './routes/api/admin/stars/leads'
import { Route as ApiAdminStarsFetchRouteImport } from './routes/api/admin/stars/fetch'
import { Route as ApiAdminStarsDigestRouteImport } from './routes/api/admin/stars/digest'
import { Route as ApiAdminMediaUploadRouteImport } from './routes/api/admin/media/upload'
import { Route as ApiAdminMediaRegisterRouteImport } from './routes/api/admin/media/register'
import { Route as ApiAdminMediaMoveRouteImport } from './routes/api/admin/media/move'
import { Route as ApiAdminMediaListRouteImport } from './routes/api/admin/media/list'
import { Route as ApiAdminMediaDownloadRouteImport } from './routes/api/admin/media/download'
import { Route as ApiAdminMediaDeleteRouteImport } from './routes/api/admin/media/delete'
import { Route as ApiAdminMediaCreateFolderRouteImport } from './routes/api/admin/media/create-folder'
import { Route as ApiAdminKanbanUpdateRouteImport } from './routes/api/admin/kanban/update'
import { Route as ApiAdminKanbanProjectsRouteImport } from './routes/api/admin/kanban/projects'
import { Route as ApiAdminKanbanItemsRouteImport } from './routes/api/admin/kanban/items'
import { Route as ApiAdminKanbanDeleteRouteImport } from './routes/api/admin/kanban/delete'
import { Route as ApiAdminKanbanCreateRouteImport } from './routes/api/admin/kanban/create'
import { Route as ApiAdminContentSaveRouteImport } from './routes/api/admin/content/save'
import { Route as ApiAdminContentRenameRouteImport } from './routes/api/admin/content/rename'
import { Route as ApiAdminContentPublishRouteImport } from './routes/api/admin/content/publish'
import { Route as ApiAdminContentPendingPrRouteImport } from './routes/api/admin/content/pending-pr'
import { Route as ApiAdminContentListDraftsRouteImport } from './routes/api/admin/content/list-drafts'
import { Route as ApiAdminContentListRouteImport } from './routes/api/admin/content/list'
import { Route as ApiAdminContentHistoryRouteImport } from './routes/api/admin/content/history'
import { Route as ApiAdminContentGetBranchFileRouteImport } from './routes/api/admin/content/get-branch-file'
import { Route as ApiAdminContentDuplicateRouteImport } from './routes/api/admin/content/duplicate'
import { Route as ApiAdminContentDeleteRouteImport } from './routes/api/admin/content/delete'
import { Route as ApiAdminContentCreateRouteImport } from './routes/api/admin/content/create'
import { Route as ApiAdminContentAuditRouteImport } from './routes/api/admin/content/audit'
import { Route as ApiAdminBlogUploadImageRouteImport } from './routes/api/admin/blog/upload-image'

const UpdatePasswordRoute = UpdatePasswordRouteImport.update({
  id: '/update-password',
  path: '/update-password',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ViewRouteRoute = ViewRouteRouteImport.update({
  id: '/_view',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangelogIndexRoute = ChangelogIndexRouteImport.update({
  id: '/changelog/',
  path: '/changelog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangelogVersionRoute = ChangelogVersionRouteImport.update({
  id: '/changelog/$version',
  path: '/changelog/$version',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTemplatesRoute = ApiTemplatesRouteImport.update({
  id: '/api/templates',
  path: '/api/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiShortcutsRoute = ApiShortcutsRouteImport.update({
  id: '/api/shortcuts',
  path: '/api/shortcuts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMediaUploadRoute = ApiMediaUploadRouteImport.update({
  id: '/api/media-upload',
  path: '/api/media-upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ViewAppRouteRoute = ViewAppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => ViewRouteRoute,
} as any)
const ViewAppIndexRoute = ViewAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ViewAppRouteRoute,
} as any)
const ApiWebhooksSlackInteractiveRoute =
  ApiWebhooksSlackInteractiveRouteImport.update({
    id: '/api/webhooks/slack-interactive',
    path: '/api/webhooks/slack-interactive',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiTweetIdRoute = ApiTweetIdRouteImport.update({
  id: '/api/tweet/$id',
  path: '/api/tweet/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAssetsSplatRoute = ApiAssetsSplatRouteImport.update({
  id: '/api/assets/$',
  path: '/api/assets/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ViewDownloadAppleSiliconRoute =
  ViewDownloadAppleSiliconRouteImport.update({
    id: '/download/apple-silicon',
    path: '/download/apple-silicon',
    getParentRoute: () => ViewRouteRoute,
  } as any)
const ViewDownloadAppleIntelRoute = ViewDownloadAppleIntelRouteImport.update({
  id: '/download/apple-intel',
  path: '/download/apple-intel',
  getParentRoute: () => ViewRouteRoute,
} as any)
const ViewCallbackSignoutRoute = ViewCallbackSignoutRouteImport.update({
  id: '/callback/signout',
  path: '/callback/signout',
  getParentRoute: () => ViewRouteRoute,
} as any)
const ViewCallbackIntegrationRoute = ViewCallbackIntegrationRouteImport.update({
  id: '/callback/integration',
  path: '/callback/integration',
  getParentRoute: () => ViewRouteRoute,
} as any)
const ViewCallbackBillingRoute = ViewCallbackBillingRouteImport.update({
  id: '/callback/billing',
  path: '/callback/billing',
  getParentRoute: () => ViewRouteRoute,
} as any)
const ViewCallbackAuthRoute = ViewCallbackAuthRouteImport.update({
  id: '/callback/auth',
  path: '/callback/auth',
  getParentRoute: () => ViewRouteRoute,
} as any)
const ViewAppSwitchPlanRoute = ViewAppSwitchPlanRouteImport.update({
  id: '/switch-plan',
  path: '/switch-plan',
  getParentRoute: () => ViewAppRouteRoute,
} as any)
const ViewAppPortalRoute = ViewAppPortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => ViewAppRouteRoute,
} as any)
const ViewAppIntegrationRoute = ViewAppIntegrationRouteImport.update({
  id: '/integration',
  path: '/integration',
  getParentRoute: () => ViewAppRouteRoute,
} as any)
const ViewAppCheckoutRoute = ViewAppCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => ViewAppRouteRoute,
} as any)
const ViewAppAccountRoute = ViewAppAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => ViewAppRouteRoute,
} as any)
const ApiOgBlogSlugRoute = ApiOgBlogSlugRouteImport.update({
  id: '/api/og/blog/$slug',
  path: '/api/og/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminStarsResearchRoute = ApiAdminStarsResearchRouteImport.update({
  id: '/api/admin/stars/research',
  path: '/api/admin/stars/research',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminStarsPipelineRoute = ApiAdminStarsPipelineRouteImport.update({
  id: '/api/admin/stars/pipeline',
  path: '/api/admin/stars/pipeline',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminStarsLeadsRoute = ApiAdminStarsLeadsRouteImport.update({
  id: '/api/admin/stars/leads',
  path: '/api/admin/stars/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminStarsFetchRoute = ApiAdminStarsFetchRouteImport.update({
  id: '/api/admin/stars/fetch',
  path: '/api/admin/stars/fetch',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminStarsDigestRoute = ApiAdminStarsDigestRouteImport.update({
  id: '/api/admin/stars/digest',
  path: '/api/admin/stars/digest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminMediaUploadRoute = ApiAdminMediaUploadRouteImport.update({
  id: '/api/admin/media/upload',
  path: '/api/admin/media/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminMediaRegisterRoute = ApiAdminMediaRegisterRouteImport.update({
  id: '/api/admin/media/register',
  path: '/api/admin/media/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminMediaMoveRoute = ApiAdminMediaMoveRouteImport.update({
  id: '/api/admin/media/move',
  path: '/api/admin/media/move',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminMediaListRoute = ApiAdminMediaListRouteImport.update({
  id: '/api/admin/media/list',
  path: '/api/admin/media/list',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminMediaDownloadRoute = ApiAdminMediaDownloadRouteImport.update({
  id: '/api/admin/media/download',
  path: '/api/admin/media/download',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminMediaDeleteRoute = ApiAdminMediaDeleteRouteImport.update({
  id: '/api/admin/media/delete',
  path: '/api/admin/media/delete',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminMediaCreateFolderRoute =
  ApiAdminMediaCreateFolderRouteImport.update({
    id: '/api/admin/media/create-folder',
    path: '/api/admin/media/create-folder',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAdminKanbanUpdateRoute = ApiAdminKanbanUpdateRouteImport.update({
  id: '/api/admin/kanban/update',
  path: '/api/admin/kanban/update',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminKanbanProjectsRoute = ApiAdminKanbanProjectsRouteImport.update({
  id: '/api/admin/kanban/projects',
  path: '/api/admin/kanban/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminKanbanItemsRoute = ApiAdminKanbanItemsRouteImport.update({
  id: '/api/admin/kanban/items',
  path: '/api/admin/kanban/items',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminKanbanDeleteRoute = ApiAdminKanbanDeleteRouteImport.update({
  id: '/api/admin/kanban/delete',
  path: '/api/admin/kanban/delete',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminKanbanCreateRoute = ApiAdminKanbanCreateRouteImport.update({
  id: '/api/admin/kanban/create',
  path: '/api/admin/kanban/create',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminContentSaveRoute = ApiAdminContentSaveRouteImport.update({
  id: '/api/admin/content/save',
  path: '/api/admin/content/save',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminContentRenameRoute = ApiAdminContentRenameRouteImport.update({
  id: '/api/admin/content/rename',
  path: '/api/admin/content/rename',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminContentPublishRoute = ApiAdminContentPublishRouteImport.update({
  id: '/api/admin/content/publish',
  path: '/api/admin/content/publish',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminContentPendingPrRoute =
  ApiAdminContentPendingPrRouteImport.update({
    id: '/api/admin/content/pending-pr',
    path: '/api/admin/content/pending-pr',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAdminContentListDraftsRoute =
  ApiAdminContentListDraftsRouteImport.update({
    id: '/api/admin/content/list-drafts',
    path: '/api/admin/content/list-drafts',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAdminContentListRoute = ApiAdminContentListRouteImport.update({
  id: '/api/admin/content/list',
  path: '/api/admin/content/list',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminContentHistoryRoute = ApiAdminContentHistoryRouteImport.update({
  id: '/api/admin/content/history',
  path: '/api/admin/content/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminContentGetBranchFileRoute =
  ApiAdminContentGetBranchFileRouteImport.update({
    id: '/api/admin/content/get-branch-file',
    path: '/api/admin/content/get-branch-file',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAdminContentDuplicateRoute =
  ApiAdminContentDuplicateRouteImport.update({
    id: '/api/admin/content/duplicate',
    path: '/api/admin/content/duplicate',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAdminContentDeleteRoute = ApiAdminContentDeleteRouteImport.update({
  id: '/api/admin/content/delete',
  path: '/api/admin/content/delete',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminContentCreateRoute = ApiAdminContentCreateRouteImport.update({
  id: '/api/admin/content/create',
  path: '/api/admin/content/create',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminContentAuditRoute = ApiAdminContentAuditRouteImport.update({
  id: '/api/admin/content/audit',
  path: '/api/admin/content/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminBlogUploadImageRoute = ApiAdminBlogUploadImageRouteImport.update({
  id: '/api/admin/blog/upload-image',
  path: '/api/admin/blog/upload-image',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/update-password': typeof UpdatePasswordRoute
  '/app': typeof ViewAppRouteRouteWithChildren
  '/api/media-upload': typeof ApiMediaUploadRoute
  '/api/shortcuts': typeof ApiShortcutsRoute
  '/api/templates': typeof ApiTemplatesRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/changelog/$version': typeof ChangelogVersionRoute
  '/blog/': typeof BlogIndexRoute
  '/changelog/': typeof ChangelogIndexRoute
  '/app/account': typeof ViewAppAccountRoute
  '/app/checkout': typeof ViewAppCheckoutRoute
  '/app/integration': typeof ViewAppIntegrationRoute
  '/app/portal': typeof ViewAppPortalRoute
  '/app/switch-plan': typeof ViewAppSwitchPlanRoute
  '/callback/auth': typeof ViewCallbackAuthRoute
  '/callback/billing': typeof ViewCallbackBillingRoute
  '/callback/integration': typeof ViewCallbackIntegrationRoute
  '/callback/signout': typeof ViewCallbackSignoutRoute
  '/download/apple-intel': typeof ViewDownloadAppleIntelRoute
  '/download/apple-silicon': typeof ViewDownloadAppleSiliconRoute
  '/api/assets/$': typeof ApiAssetsSplatRoute
  '/api/tweet/$id': typeof ApiTweetIdRoute
  '/api/webhooks/slack-interactive': typeof ApiWebhooksSlackInteractiveRoute
  '/app/': typeof ViewAppIndexRoute
  '/api/admin/blog/upload-image': typeof ApiAdminBlogUploadImageRoute
  '/api/admin/content/audit': typeof ApiAdminContentAuditRoute
  '/api/admin/content/create': typeof ApiAdminContentCreateRoute
  '/api/admin/content/delete': typeof ApiAdminContentDeleteRoute
  '/api/admin/content/duplicate': typeof ApiAdminContentDuplicateRoute
  '/api/admin/content/get-branch-file': typeof ApiAdminContentGetBranchFileRoute
  '/api/admin/content/history': typeof ApiAdminContentHistoryRoute
  '/api/admin/content/list': typeof ApiAdminContentListRoute
  '/api/admin/content/list-drafts': typeof ApiAdminContentListDraftsRoute
  '/api/admin/content/pending-pr': typeof ApiAdminContentPendingPrRoute
  '/api/admin/content/publish': typeof ApiAdminContentPublishRoute
  '/api/admin/content/rename': typeof ApiAdminContentRenameRoute
  '/api/admin/content/save': typeof ApiAdminContentSaveRoute
  '/api/admin/kanban/create': typeof ApiAdminKanbanCreateRoute
  '/api/admin/kanban/delete': typeof ApiAdminKanbanDeleteRoute
  '/api/admin/kanban/items': typeof ApiAdminKanbanItemsRoute
  '/api/admin/kanban/projects': typeof ApiAdminKanbanProjectsRoute
  '/api/admin/kanban/update': typeof ApiAdminKanbanUpdateRoute
  '/api/admin/media/create-folder': typeof ApiAdminMediaCreateFolderRoute
  '/api/admin/media/delete': typeof ApiAdminMediaDeleteRoute
  '/api/admin/media/download': typeof ApiAdminMediaDownloadRoute
  '/api/admin/media/list': typeof ApiAdminMediaListRoute
  '/api/admin/media/move': typeof ApiAdminMediaMoveRoute
  '/api/admin/media/register': typeof ApiAdminMediaRegisterRoute
  '/api/admin/media/upload': typeof ApiAdminMediaUploadRoute
  '/api/admin/stars/digest': typeof ApiAdminStarsDigestRoute
  '/api/admin/stars/fetch': typeof ApiAdminStarsFetchRoute
  '/api/admin/stars/leads': typeof ApiAdminStarsLeadsRoute
  '/api/admin/stars/pipeline': typeof ApiAdminStarsPipelineRoute
  '/api/admin/stars/research': typeof ApiAdminStarsResearchRoute
  '/api/og/blog/$slug': typeof ApiOgBlogSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/update-password': typeof UpdatePasswordRoute
  '/api/media-upload': typeof ApiMediaUploadRoute
  '/api/shortcuts': typeof ApiShortcutsRoute
  '/api/templates': typeof ApiTemplatesRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/changelog/$version': typeof ChangelogVersionRoute
  '/blog': typeof BlogIndexRoute
  '/changelog': typeof ChangelogIndexRoute
  '/app/account': typeof ViewAppAccountRoute
  '/app/checkout': typeof ViewAppCheckoutRoute
  '/app/integration': typeof ViewAppIntegrationRoute
  '/app/portal': typeof ViewAppPortalRoute
  '/app/switch-plan': typeof ViewAppSwitchPlanRoute
  '/callback/auth': typeof ViewCallbackAuthRoute
  '/callback/billing': typeof ViewCallbackBillingRoute
  '/callback/integration': typeof ViewCallbackIntegrationRoute
  '/callback/signout': typeof ViewCallbackSignoutRoute
  '/download/apple-intel': typeof ViewDownloadAppleIntelRoute
  '/download/apple-silicon': typeof ViewDownloadAppleSiliconRoute
  '/api/assets/$': typeof ApiAssetsSplatRoute
  '/api/tweet/$id': typeof ApiTweetIdRoute
  '/api/webhooks/slack-interactive': typeof ApiWebhooksSlackInteractiveRoute
  '/app': typeof ViewAppIndexRoute
  '/api/admin/blog/upload-image': typeof ApiAdminBlogUploadImageRoute
  '/api/admin/content/audit': typeof ApiAdminContentAuditRoute
  '/api/admin/content/create': typeof ApiAdminContentCreateRoute
  '/api/admin/content/delete': typeof ApiAdminContentDeleteRoute
  '/api/admin/content/duplicate': typeof ApiAdminContentDuplicateRoute
  '/api/admin/content/get-branch-file': typeof ApiAdminContentGetBranchFileRoute
  '/api/admin/content/history': typeof ApiAdminContentHistoryRoute
  '/api/admin/content/list': typeof ApiAdminContentListRoute
  '/api/admin/content/list-drafts': typeof ApiAdminContentListDraftsRoute
  '/api/admin/content/pending-pr': typeof ApiAdminContentPendingPrRoute
  '/api/admin/content/publish': typeof ApiAdminContentPublishRoute
  '/api/admin/content/rename': typeof ApiAdminContentRenameRoute
  '/api/admin/content/save': typeof ApiAdminContentSaveRoute
  '/api/admin/kanban/create': typeof ApiAdminKanbanCreateRoute
  '/api/admin/kanban/delete': typeof ApiAdminKanbanDeleteRoute
  '/api/admin/kanban/items': typeof ApiAdminKanbanItemsRoute
  '/api/admin/kanban/projects': typeof ApiAdminKanbanProjectsRoute
  '/api/admin/kanban/update': typeof ApiAdminKanbanUpdateRoute
  '/api/admin/media/create-folder': typeof ApiAdminMediaCreateFolderRoute
  '/api/admin/media/delete': typeof ApiAdminMediaDeleteRoute
  '/api/admin/media/download': typeof ApiAdminMediaDownloadRoute
  '/api/admin/media/list': typeof ApiAdminMediaListRoute
  '/api/admin/media/move': typeof ApiAdminMediaMoveRoute
  '/api/admin/media/register': typeof ApiAdminMediaRegisterRoute
  '/api/admin/media/upload': typeof ApiAdminMediaUploadRoute
  '/api/admin/stars/digest': typeof ApiAdminStarsDigestRoute
  '/api/admin/stars/fetch': typeof ApiAdminStarsFetchRoute
  '/api/admin/stars/leads': typeof ApiAdminStarsLeadsRoute
  '/api/admin/stars/pipeline': typeof ApiAdminStarsPipelineRoute
  '/api/admin/stars/research': typeof ApiAdminStarsResearchRoute
  '/api/og/blog/$slug': typeof ApiOgBlogSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_view': typeof ViewRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/update-password': typeof UpdatePasswordRoute
  '/_view/app': typeof ViewAppRouteRouteWithChildren
  '/api/media-upload': typeof ApiMediaUploadRoute
  '/api/shortcuts': typeof ApiShortcutsRoute
  '/api/templates': typeof ApiTemplatesRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/changelog/$version': typeof ChangelogVersionRoute
  '/blog/': typeof BlogIndexRoute
  '/changelog/': typeof ChangelogIndexRoute
  '/_view/app/account': typeof ViewAppAccountRoute
  '/_view/app/checkout': typeof ViewAppCheckoutRoute
  '/_view/app/integration': typeof ViewAppIntegrationRoute
  '/_view/app/portal': typeof ViewAppPortalRoute
  '/_view/app/switch-plan': typeof ViewAppSwitchPlanRoute
  '/_view/callback/auth': typeof ViewCallbackAuthRoute
  '/_view/callback/billing': typeof ViewCallbackBillingRoute
  '/_view/callback/integration': typeof ViewCallbackIntegrationRoute
  '/_view/callback/signout': typeof ViewCallbackSignoutRoute
  '/_view/download/apple-intel': typeof ViewDownloadAppleIntelRoute
  '/_view/download/apple-silicon': typeof ViewDownloadAppleSiliconRoute
  '/api/assets/$': typeof ApiAssetsSplatRoute
  '/api/tweet/$id': typeof ApiTweetIdRoute
  '/api/webhooks/slack-interactive': typeof ApiWebhooksSlackInteractiveRoute
  '/_view/app/': typeof ViewAppIndexRoute
  '/api/admin/blog/upload-image': typeof ApiAdminBlogUploadImageRoute
  '/api/admin/content/audit': typeof ApiAdminContentAuditRoute
  '/api/admin/content/create': typeof ApiAdminContentCreateRoute
  '/api/admin/content/delete': typeof ApiAdminContentDeleteRoute
  '/api/admin/content/duplicate': typeof ApiAdminContentDuplicateRoute
  '/api/admin/content/get-branch-file': typeof ApiAdminContentGetBranchFileRoute
  '/api/admin/content/history': typeof ApiAdminContentHistoryRoute
  '/api/admin/content/list': typeof ApiAdminContentListRoute
  '/api/admin/content/list-drafts': typeof ApiAdminContentListDraftsRoute
  '/api/admin/content/pending-pr': typeof ApiAdminContentPendingPrRoute
  '/api/admin/content/publish': typeof ApiAdminContentPublishRoute
  '/api/admin/content/rename': typeof ApiAdminContentRenameRoute
  '/api/admin/content/save': typeof ApiAdminContentSaveRoute
  '/api/admin/kanban/create': typeof ApiAdminKanbanCreateRoute
  '/api/admin/kanban/delete': typeof ApiAdminKanbanDeleteRoute
  '/api/admin/kanban/items': typeof ApiAdminKanbanItemsRoute
  '/api/admin/kanban/projects': typeof ApiAdminKanbanProjectsRoute
  '/api/admin/kanban/update': typeof ApiAdminKanbanUpdateRoute
  '/api/admin/media/create-folder': typeof ApiAdminMediaCreateFolderRoute
  '/api/admin/media/delete': typeof ApiAdminMediaDeleteRoute
  '/api/admin/media/download': typeof ApiAdminMediaDownloadRoute
  '/api/admin/media/list': typeof ApiAdminMediaListRoute
  '/api/admin/media/move': typeof ApiAdminMediaMoveRoute
  '/api/admin/media/register': typeof ApiAdminMediaRegisterRoute
  '/api/admin/media/upload': typeof ApiAdminMediaUploadRoute
  '/api/admin/stars/digest': typeof ApiAdminStarsDigestRoute
  '/api/admin/stars/fetch': typeof ApiAdminStarsFetchRoute
  '/api/admin/stars/leads': typeof ApiAdminStarsLeadsRoute
  '/api/admin/stars/pipeline': typeof ApiAdminStarsPipelineRoute
  '/api/admin/stars/research': typeof ApiAdminStarsResearchRoute
  '/api/og/blog/$slug': typeof ApiOgBlogSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/privacy'
    | '/reset-password'
    | '/terms'
    | '/update-password'
    | '/app'
    | '/api/media-upload'
    | '/api/shortcuts'
    | '/api/templates'
    | '/blog/$slug'
    | '/changelog/$version'
    | '/blog/'
    | '/changelog/'
    | '/app/account'
    | '/app/checkout'
    | '/app/integration'
    | '/app/portal'
    | '/app/switch-plan'
    | '/callback/auth'
    | '/callback/billing'
    | '/callback/integration'
    | '/callback/signout'
    | '/download/apple-intel'
    | '/download/apple-silicon'
    | '/api/assets/$'
    | '/api/tweet/$id'
    | '/api/webhooks/slack-interactive'
    | '/app/'
    | '/api/admin/blog/upload-image'
    | '/api/admin/content/audit'
    | '/api/admin/content/create'
    | '/api/admin/content/delete'
    | '/api/admin/content/duplicate'
    | '/api/admin/content/get-branch-file'
    | '/api/admin/content/history'
    | '/api/admin/content/list'
    | '/api/admin/content/list-drafts'
    | '/api/admin/content/pending-pr'
    | '/api/admin/content/publish'
    | '/api/admin/content/rename'
    | '/api/admin/content/save'
    | '/api/admin/kanban/create'
    | '/api/admin/kanban/delete'
    | '/api/admin/kanban/items'
    | '/api/admin/kanban/projects'
    | '/api/admin/kanban/update'
    | '/api/admin/media/create-folder'
    | '/api/admin/media/delete'
    | '/api/admin/media/download'
    | '/api/admin/media/list'
    | '/api/admin/media/move'
    | '/api/admin/media/register'
    | '/api/admin/media/upload'
    | '/api/admin/stars/digest'
    | '/api/admin/stars/fetch'
    | '/api/admin/stars/leads'
    | '/api/admin/stars/pipeline'
    | '/api/admin/stars/research'
    | '/api/og/blog/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/privacy'
    | '/reset-password'
    | '/terms'
    | '/update-password'
    | '/api/media-upload'
    | '/api/shortcuts'
    | '/api/templates'
    | '/blog/$slug'
    | '/changelog/$version'
    | '/blog'
    | '/changelog'
    | '/app/account'
    | '/app/checkout'
    | '/app/integration'
    | '/app/portal'
    | '/app/switch-plan'
    | '/callback/auth'
    | '/callback/billing'
    | '/callback/integration'
    | '/callback/signout'
    | '/download/apple-intel'
    | '/download/apple-silicon'
    | '/api/assets/$'
    | '/api/tweet/$id'
    | '/api/webhooks/slack-interactive'
    | '/app'
    | '/api/admin/blog/upload-image'
    | '/api/admin/content/audit'
    | '/api/admin/content/create'
    | '/api/admin/content/delete'
    | '/api/admin/content/duplicate'
    | '/api/admin/content/get-branch-file'
    | '/api/admin/content/history'
    | '/api/admin/content/list'
    | '/api/admin/content/list-drafts'
    | '/api/admin/content/pending-pr'
    | '/api/admin/content/publish'
    | '/api/admin/content/rename'
    | '/api/admin/content/save'
    | '/api/admin/kanban/create'
    | '/api/admin/kanban/delete'
    | '/api/admin/kanban/items'
    | '/api/admin/kanban/projects'
    | '/api/admin/kanban/update'
    | '/api/admin/media/create-folder'
    | '/api/admin/media/delete'
    | '/api/admin/media/download'
    | '/api/admin/media/list'
    | '/api/admin/media/move'
    | '/api/admin/media/register'
    | '/api/admin/media/upload'
    | '/api/admin/stars/digest'
    | '/api/admin/stars/fetch'
    | '/api/admin/stars/leads'
    | '/api/admin/stars/pipeline'
    | '/api/admin/stars/research'
    | '/api/og/blog/$slug'
  id:
    | '__root__'
    | '/'
    | '/_view'
    | '/auth'
    | '/privacy'
    | '/reset-password'
    | '/terms'
    | '/update-password'
    | '/_view/app'
    | '/api/media-upload'
    | '/api/shortcuts'
    | '/api/templates'
    | '/blog/$slug'
    | '/changelog/$version'
    | '/blog/'
    | '/changelog/'
    | '/_view/app/account'
    | '/_view/app/checkout'
    | '/_view/app/integration'
    | '/_view/app/portal'
    | '/_view/app/switch-plan'
    | '/_view/callback/auth'
    | '/_view/callback/billing'
    | '/_view/callback/integration'
    | '/_view/callback/signout'
    | '/_view/download/apple-intel'
    | '/_view/download/apple-silicon'
    | '/api/assets/$'
    | '/api/tweet/$id'
    | '/api/webhooks/slack-interactive'
    | '/_view/app/'
    | '/api/admin/blog/upload-image'
    | '/api/admin/content/audit'
    | '/api/admin/content/create'
    | '/api/admin/content/delete'
    | '/api/admin/content/duplicate'
    | '/api/admin/content/get-branch-file'
    | '/api/admin/content/history'
    | '/api/admin/content/list'
    | '/api/admin/content/list-drafts'
    | '/api/admin/content/pending-pr'
    | '/api/admin/content/publish'
    | '/api/admin/content/rename'
    | '/api/admin/content/save'
    | '/api/admin/kanban/create'
    | '/api/admin/kanban/delete'
    | '/api/admin/kanban/items'
    | '/api/admin/kanban/projects'
    | '/api/admin/kanban/update'
    | '/api/admin/media/create-folder'
    | '/api/admin/media/delete'
    | '/api/admin/media/download'
    | '/api/admin/media/list'
    | '/api/admin/media/move'
    | '/api/admin/media/register'
    | '/api/admin/media/upload'
    | '/api/admin/stars/digest'
    | '/api/admin/stars/fetch'
    | '/api/admin/stars/leads'
    | '/api/admin/stars/pipeline'
    | '/api/admin/stars/research'
    | '/api/og/blog/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ViewRouteRoute: typeof ViewRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TermsRoute: typeof TermsRoute
  UpdatePasswordRoute: typeof UpdatePasswordRoute
  ApiMediaUploadRoute: typeof ApiMediaUploadRoute
  ApiShortcutsRoute: typeof ApiShortcutsRoute
  ApiTemplatesRoute: typeof ApiTemplatesRoute
  BlogSlugRoute: typeof BlogSlugRoute
  ChangelogVersionRoute: typeof ChangelogVersionRoute
  BlogIndexRoute: typeof BlogIndexRoute
  ChangelogIndexRoute: typeof ChangelogIndexRoute
  ApiAssetsSplatRoute: typeof ApiAssetsSplatRoute
  ApiTweetIdRoute: typeof ApiTweetIdRoute
  ApiWebhooksSlackInteractiveRoute: typeof ApiWebhooksSlackInteractiveRoute
  ApiAdminBlogUploadImageRoute: typeof ApiAdminBlogUploadImageRoute
  ApiAdminContentAuditRoute: typeof ApiAdminContentAuditRoute
  ApiAdminContentCreateRoute: typeof ApiAdminContentCreateRoute
  ApiAdminContentDeleteRoute: typeof ApiAdminContentDeleteRoute
  ApiAdminContentDuplicateRoute: typeof ApiAdminContentDuplicateRoute
  ApiAdminContentGetBranchFileRoute: typeof ApiAdminContentGetBranchFileRoute
  ApiAdminContentHistoryRoute: typeof ApiAdminContentHistoryRoute
  ApiAdminContentListRoute: typeof ApiAdminContentListRoute
  ApiAdminContentListDraftsRoute: typeof ApiAdminContentListDraftsRoute
  ApiAdminContentPendingPrRoute: typeof ApiAdminContentPendingPrRoute
  ApiAdminContentPublishRoute: typeof ApiAdminContentPublishRoute
  ApiAdminContentRenameRoute: typeof ApiAdminContentRenameRoute
  ApiAdminContentSaveRoute: typeof ApiAdminContentSaveRoute
  ApiAdminKanbanCreateRoute: typeof ApiAdminKanbanCreateRoute
  ApiAdminKanbanDeleteRoute: typeof ApiAdminKanbanDeleteRoute
  ApiAdminKanbanItemsRoute: typeof ApiAdminKanbanItemsRoute
  ApiAdminKanbanProjectsRoute: typeof ApiAdminKanbanProjectsRoute
  ApiAdminKanbanUpdateRoute: typeof ApiAdminKanbanUpdateRoute
  ApiAdminMediaCreateFolderRoute: typeof ApiAdminMediaCreateFolderRoute
  ApiAdminMediaDeleteRoute: typeof ApiAdminMediaDeleteRoute
  ApiAdminMediaDownloadRoute: typeof ApiAdminMediaDownloadRoute
  ApiAdminMediaListRoute: typeof ApiAdminMediaListRoute
  ApiAdminMediaMoveRoute: typeof ApiAdminMediaMoveRoute
  ApiAdminMediaRegisterRoute: typeof ApiAdminMediaRegisterRoute
  ApiAdminMediaUploadRoute: typeof ApiAdminMediaUploadRoute
  ApiAdminStarsDigestRoute: typeof ApiAdminStarsDigestRoute
  ApiAdminStarsFetchRoute: typeof ApiAdminStarsFetchRoute
  ApiAdminStarsLeadsRoute: typeof ApiAdminStarsLeadsRoute
  ApiAdminStarsPipelineRoute: typeof ApiAdminStarsPipelineRoute
  ApiAdminStarsResearchRoute: typeof ApiAdminStarsResearchRoute
  ApiOgBlogSlugRoute: typeof ApiOgBlogSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/update-password': {
      id: '/update-password'
      path: '/update-password'
      fullPath: '/update-password'
      preLoaderRoute: typeof UpdatePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_view': {
      id: '/_view'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ViewRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changelog/': {
      id: '/changelog/'
      path: '/changelog'
      fullPath: '/changelog/'
      preLoaderRoute: typeof ChangelogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changelog/$version': {
      id: '/changelog/$version'
      path: '/changelog/$version'
      fullPath: '/changelog/$version'
      preLoaderRoute: typeof ChangelogVersionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/templates': {
      id: '/api/templates'
      path: '/api/templates'
      fullPath: '/api/templates'
      preLoaderRoute: typeof ApiTemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/shortcuts': {
      id: '/api/shortcuts'
      path: '/api/shortcuts'
      fullPath: '/api/shortcuts'
      preLoaderRoute: typeof ApiShortcutsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/media-upload': {
      id: '/api/media-upload'
      path: '/api/media-upload'
      fullPath: '/api/media-upload'
      preLoaderRoute: typeof ApiMediaUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_view/app': {
      id: '/_view/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof ViewAppRouteRouteImport
      parentRoute: typeof ViewRouteRoute
    }
    '/_view/app/': {
      id: '/_view/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof ViewAppIndexRouteImport
      parentRoute: typeof ViewAppRouteRoute
    }
    '/api/webhooks/slack-interactive': {
      id: '/api/webhooks/slack-interactive'
      path: '/api/webhooks/slack-interactive'
      fullPath: '/api/webhooks/slack-interactive'
      preLoaderRoute: typeof ApiWebhooksSlackInteractiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tweet/$id': {
      id: '/api/tweet/$id'
      path: '/api/tweet/$id'
      fullPath: '/api/tweet/$id'
      preLoaderRoute: typeof ApiTweetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/assets/$': {
      id: '/api/assets/$'
      path: '/api/assets/$'
      fullPath: '/api/assets/$'
      preLoaderRoute: typeof ApiAssetsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_view/download/apple-silicon': {
      id: '/_view/download/apple-silicon'
      path: '/download/apple-silicon'
      fullPath: '/download/apple-silicon'
      preLoaderRoute: typeof ViewDownloadAppleSiliconRouteImport
      parentRoute: typeof ViewRouteRoute
    }
    '/_view/download/apple-intel': {
      id: '/_view/download/apple-intel'
      path: '/download/apple-intel'
      fullPath: '/download/apple-intel'
      preLoaderRoute: typeof ViewDownloadAppleIntelRouteImport
      parentRoute: typeof ViewRouteRoute
    }
    '/_view/callback/signout': {
      id: '/_view/callback/signout'
      path: '/callback/signout'
      fullPath: '/callback/signout'
      preLoaderRoute: typeof ViewCallbackSignoutRouteImport
      parentRoute: typeof ViewRouteRoute
    }
    '/_view/callback/integration': {
      id: '/_view/callback/integration'
      path: '/callback/integration'
      fullPath: '/callback/integration'
      preLoaderRoute: typeof ViewCallbackIntegrationRouteImport
      parentRoute: typeof ViewRouteRoute
    }
    '/_view/callback/billing': {
      id: '/_view/callback/billing'
      path: '/callback/billing'
      fullPath: '/callback/billing'
      preLoaderRoute: typeof ViewCallbackBillingRouteImport
      parentRoute: typeof ViewRouteRoute
    }
    '/_view/callback/auth': {
      id: '/_view/callback/auth'
      path: '/callback/auth'
      fullPath: '/callback/auth'
      preLoaderRoute: typeof ViewCallbackAuthRouteImport
      parentRoute: typeof ViewRouteRoute
    }
    '/_view/app/switch-plan': {
      id: '/_view/app/switch-plan'
      path: '/switch-plan'
      fullPath: '/app/switch-plan'
      preLoaderRoute: typeof ViewAppSwitchPlanRouteImport
      parentRoute: typeof ViewAppRouteRoute
    }
    '/_view/app/portal': {
      id: '/_view/app/portal'
      path: '/portal'
      fullPath: '/app/portal'
      preLoaderRoute: typeof ViewAppPortalRouteImport
      parentRoute: typeof ViewAppRouteRoute
    }
    '/_view/app/integration': {
      id: '/_view/app/integration'
      path: '/integration'
      fullPath: '/app/integration'
      preLoaderRoute: typeof ViewAppIntegrationRouteImport
      parentRoute: typeof ViewAppRouteRoute
    }
    '/_view/app/checkout': {
      id: '/_view/app/checkout'
      path: '/checkout'
      fullPath: '/app/checkout'
      preLoaderRoute: typeof ViewAppCheckoutRouteImport
      parentRoute: typeof ViewAppRouteRoute
    }
    '/_view/app/account': {
      id: '/_view/app/account'
      path: '/account'
      fullPath: '/app/account'
      preLoaderRoute: typeof ViewAppAccountRouteImport
      parentRoute: typeof ViewAppRouteRoute
    }
    '/api/og/blog/$slug': {
      id: '/api/og/blog/$slug'
      path: '/api/og/blog/$slug'
      fullPath: '/api/og/blog/$slug'
      preLoaderRoute: typeof ApiOgBlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/stars/research': {
      id: '/api/admin/stars/research'
      path: '/api/admin/stars/research'
      fullPath: '/api/admin/stars/research'
      preLoaderRoute: typeof ApiAdminStarsResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/stars/pipeline': {
      id: '/api/admin/stars/pipeline'
      path: '/api/admin/stars/pipeline'
      fullPath: '/api/admin/stars/pipeline'
      preLoaderRoute: typeof ApiAdminStarsPipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/stars/leads': {
      id: '/api/admin/stars/leads'
      path: '/api/admin/stars/leads'
      fullPath: '/api/admin/stars/leads'
      preLoaderRoute: typeof ApiAdminStarsLeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/stars/fetch': {
      id: '/api/admin/stars/fetch'
      path: '/api/admin/stars/fetch'
      fullPath: '/api/admin/stars/fetch'
      preLoaderRoute: typeof ApiAdminStarsFetchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/stars/digest': {
      id: '/api/admin/stars/digest'
      path: '/api/admin/stars/digest'
      fullPath: '/api/admin/stars/digest'
      preLoaderRoute: typeof ApiAdminStarsDigestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/media/upload': {
      id: '/api/admin/media/upload'
      path: '/api/admin/media/upload'
      fullPath: '/api/admin/media/upload'
      preLoaderRoute: typeof ApiAdminMediaUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/media/register': {
      id: '/api/admin/media/register'
      path: '/api/admin/media/register'
      fullPath: '/api/admin/media/register'
      preLoaderRoute: typeof ApiAdminMediaRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/media/move': {
      id: '/api/admin/media/move'
      path: '/api/admin/media/move'
      fullPath: '/api/admin/media/move'
      preLoaderRoute: typeof ApiAdminMediaMoveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/media/list': {
      id: '/api/admin/media/list'
      path: '/api/admin/media/list'
      fullPath: '/api/admin/media/list'
      preLoaderRoute: typeof ApiAdminMediaListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/media/download': {
      id: '/api/admin/media/download'
      path: '/api/admin/media/download'
      fullPath: '/api/admin/media/download'
      preLoaderRoute: typeof ApiAdminMediaDownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/media/delete': {
      id: '/api/admin/media/delete'
      path: '/api/admin/media/delete'
      fullPath: '/api/admin/media/delete'
      preLoaderRoute: typeof ApiAdminMediaDeleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/media/create-folder': {
      id: '/api/admin/media/create-folder'
      path: '/api/admin/media/create-folder'
      fullPath: '/api/admin/media/create-folder'
      preLoaderRoute: typeof ApiAdminMediaCreateFolderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/kanban/update': {
      id: '/api/admin/kanban/update'
      path: '/api/admin/kanban/update'
      fullPath: '/api/admin/kanban/update'
      preLoaderRoute: typeof ApiAdminKanbanUpdateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/kanban/projects': {
      id: '/api/admin/kanban/projects'
      path: '/api/admin/kanban/projects'
      fullPath: '/api/admin/kanban/projects'
      preLoaderRoute: typeof ApiAdminKanbanProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/kanban/items': {
      id: '/api/admin/kanban/items'
      path: '/api/admin/kanban/items'
      fullPath: '/api/admin/kanban/items'
      preLoaderRoute: typeof ApiAdminKanbanItemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/kanban/delete': {
      id: '/api/admin/kanban/delete'
      path: '/api/admin/kanban/delete'
      fullPath: '/api/admin/kanban/delete'
      preLoaderRoute: typeof ApiAdminKanbanDeleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/kanban/create': {
      id: '/api/admin/kanban/create'
      path: '/api/admin/kanban/create'
      fullPath: '/api/admin/kanban/create'
      preLoaderRoute: typeof ApiAdminKanbanCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/content/save': {
      id: '/api/admin/content/save'
      path: '/api/admin/content/save'
      fullPath: '/api/admin/content/save'
      preLoaderRoute: typeof ApiAdminContentSaveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/content/rename': {
      id: '/api/admin/content/rename'
      path: '/api/admin/content/rename'
      fullPath: '/api/admin/content/rename'
      preLoaderRoute: typeof ApiAdminContentRenameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/content/publish': {
      id: '/api/admin/content/publish'
      path: '/api/admin/content/publish'
      fullPath: '/api/admin/content/publish'
      preLoaderRoute: typeof ApiAdminContentPublishRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/content/pending-pr': {
      id: '/api/admin/content/pending-pr'
      path: '/api/admin/content/pending-pr'
      fullPath: '/api/admin/content/pending-pr'
      preLoaderRoute: typeof ApiAdminContentPendingPrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/content/list-drafts': {
      id: '/api/admin/content/list-drafts'
      path: '/api/admin/content/list-drafts'
      fullPath: '/api/admin/content/list-drafts'
      preLoaderRoute: typeof ApiAdminContentListDraftsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/content/list': {
      id: '/api/admin/content/list'
      path: '/api/admin/content/list'
      fullPath: '/api/admin/content/list'
      preLoaderRoute: typeof ApiAdminContentListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/content/history': {
      id: '/api/admin/content/history'
      path: '/api/admin/content/history'
      fullPath: '/api/admin/content/history'
      preLoaderRoute: typeof ApiAdminContentHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/content/get-branch-file': {
      id: '/api/admin/content/get-branch-file'
      path: '/api/admin/content/get-branch-file'
      fullPath: '/api/admin/content/get-branch-file'
      preLoaderRoute: typeof ApiAdminContentGetBranchFileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/content/duplicate': {
      id: '/api/admin/content/duplicate'
      path: '/api/admin/content/duplicate'
      fullPath: '/api/admin/content/duplicate'
      preLoaderRoute: typeof ApiAdminContentDuplicateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/content/delete': {
      id: '/api/admin/content/delete'
      path: '/api/admin/content/delete'
      fullPath: '/api/admin/content/delete'
      preLoaderRoute: typeof ApiAdminContentDeleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/content/create': {
      id: '/api/admin/content/create'
      path: '/api/admin/content/create'
      fullPath: '/api/admin/content/create'
      preLoaderRoute: typeof ApiAdminContentCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/content/audit': {
      id: '/api/admin/content/audit'
      path: '/api/admin/content/audit'
      fullPath: '/api/admin/content/audit'
      preLoaderRoute: typeof ApiAdminContentAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/blog/upload-image': {
      id: '/api/admin/blog/upload-image'
      path: '/api/admin/blog/upload-image'
      fullPath: '/api/admin/blog/upload-image'
      preLoaderRoute: typeof ApiAdminBlogUploadImageRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ViewAppRouteRouteChildren {
  ViewAppAccountRoute: typeof ViewAppAccountRoute
  ViewAppCheckoutRoute: typeof ViewAppCheckoutRoute
  ViewAppIntegrationRoute: typeof ViewAppIntegrationRoute
  ViewAppPortalRoute: typeof ViewAppPortalRoute
  ViewAppSwitchPlanRoute: typeof ViewAppSwitchPlanRoute
  ViewAppIndexRoute: typeof ViewAppIndexRoute
}

const ViewAppRouteRouteChildren: ViewAppRouteRouteChildren = {
  ViewAppAccountRoute: ViewAppAccountRoute,
  ViewAppCheckoutRoute: ViewAppCheckoutRoute,
  ViewAppIntegrationRoute: ViewAppIntegrationRoute,
  ViewAppPortalRoute: ViewAppPortalRoute,
  ViewAppSwitchPlanRoute: ViewAppSwitchPlanRoute,
  ViewAppIndexRoute: ViewAppIndexRoute,
}

const ViewAppRouteRouteWithChildren = ViewAppRouteRoute._addFileChildren(
  ViewAppRouteRouteChildren,
)

interface ViewRouteRouteChildren {
  ViewAppRouteRoute: typeof ViewAppRouteRouteWithChildren
  ViewCallbackAuthRoute: typeof ViewCallbackAuthRoute
  ViewCallbackBillingRoute: typeof ViewCallbackBillingRoute
  ViewCallbackIntegrationRoute: typeof ViewCallbackIntegrationRoute
  ViewCallbackSignoutRoute: typeof ViewCallbackSignoutRoute
  ViewDownloadAppleIntelRoute: typeof ViewDownloadAppleIntelRoute
  ViewDownloadAppleSiliconRoute: typeof ViewDownloadAppleSiliconRoute
}

const ViewRouteRouteChildren: ViewRouteRouteChildren = {
  ViewAppRouteRoute: ViewAppRouteRouteWithChildren,
  ViewCallbackAuthRoute: ViewCallbackAuthRoute,
  ViewCallbackBillingRoute: ViewCallbackBillingRoute,
  ViewCallbackIntegrationRoute: ViewCallbackIntegrationRoute,
  ViewCallbackSignoutRoute: ViewCallbackSignoutRoute,
  ViewDownloadAppleIntelRoute: ViewDownloadAppleIntelRoute,
  ViewDownloadAppleSiliconRoute: ViewDownloadAppleSiliconRoute,
}

const ViewRouteRouteWithChildren = ViewRouteRoute._addFileChildren(
  ViewRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ViewRouteRoute: ViewRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TermsRoute: TermsRoute,
  UpdatePasswordRoute: UpdatePasswordRoute,
  ApiMediaUploadRoute: ApiMediaUploadRoute,
  ApiShortcutsRoute: ApiShortcutsRoute,
  ApiTemplatesRoute: ApiTemplatesRoute,
  BlogSlugRoute: BlogSlugRoute,
  ChangelogVersionRoute: ChangelogVersionRoute,
  BlogIndexRoute: BlogIndexRoute,
  ChangelogIndexRoute: ChangelogIndexRoute,
  ApiAssetsSplatRoute: ApiAssetsSplatRoute,
  ApiTweetIdRoute: ApiTweetIdRoute,
  ApiWebhooksSlackInteractiveRoute: ApiWebhooksSlackInteractiveRoute,
  ApiAdminBlogUploadImageRoute: ApiAdminBlogUploadImageRoute,
  ApiAdminContentAuditRoute: ApiAdminContentAuditRoute,
  ApiAdminContentCreateRoute: ApiAdminContentCreateRoute,
  ApiAdminContentDeleteRoute: ApiAdminContentDeleteRoute,
  ApiAdminContentDuplicateRoute: ApiAdminContentDuplicateRoute,
  ApiAdminContentGetBranchFileRoute: ApiAdminContentGetBranchFileRoute,
  ApiAdminContentHistoryRoute: ApiAdminContentHistoryRoute,
  ApiAdminContentListRoute: ApiAdminContentListRoute,
  ApiAdminContentListDraftsRoute: ApiAdminContentListDraftsRoute,
  ApiAdminContentPendingPrRoute: ApiAdminContentPendingPrRoute,
  ApiAdminContentPublishRoute: ApiAdminContentPublishRoute,
  ApiAdminContentRenameRoute: ApiAdminContentRenameRoute,
  ApiAdminContentSaveRoute: ApiAdminContentSaveRoute,
  ApiAdminKanbanCreateRoute: ApiAdminKanbanCreateRoute,
  ApiAdminKanbanDeleteRoute: ApiAdminKanbanDeleteRoute,
  ApiAdminKanbanItemsRoute: ApiAdminKanbanItemsRoute,
  ApiAdminKanbanProjectsRoute: ApiAdminKanbanProjectsRoute,
  ApiAdminKanbanUpdateRoute: ApiAdminKanbanUpdateRoute,
  ApiAdminMediaCreateFolderRoute: ApiAdminMediaCreateFolderRoute,
  ApiAdminMediaDeleteRoute: ApiAdminMediaDeleteRoute,
  ApiAdminMediaDownloadRoute: ApiAdminMediaDownloadRoute,
  ApiAdminMediaListRoute: ApiAdminMediaListRoute,
  ApiAdminMediaMoveRoute: ApiAdminMediaMoveRoute,
  ApiAdminMediaRegisterRoute: ApiAdminMediaRegisterRoute,
  ApiAdminMediaUploadRoute: ApiAdminMediaUploadRoute,
  ApiAdminStarsDigestRoute: ApiAdminStarsDigestRoute,
  ApiAdminStarsFetchRoute: ApiAdminStarsFetchRoute,
  ApiAdminStarsLeadsRoute: ApiAdminStarsLeadsRoute,
  ApiAdminStarsPipelineRoute: ApiAdminStarsPipelineRoute,
  ApiAdminStarsResearchRoute: ApiAdminStarsResearchRoute,
  ApiOgBlogSlugRoute: ApiOgBlogSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
